# Generated by Django 4.2.8 on 2024-01-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='assets\\img\\products'),
        ),
        migrations.AlterField(
            model_name='product_image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='assets\\img\\porducts'),
        ),
    ]
