# Generated by Django 4.2.8 on 2024-01-02 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_image_alter_product_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='assets\\img\\products'),
        ),
    ]
