# Generated by Django 4.2.8 on 2024-01-04 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_image_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail',
            old_name='product',
            new_name='producti',
        ),
    ]
