# Generated by Django 4.2.8 on 2024-01-05 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_product_detail_producti'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client_coments',
            old_name='product',
            new_name='producti',
        ),
    ]
