# Generated by Django 4.2.8 on 2024-01-08 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_rename_product_client_coments_producti'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='Set_of_accessories',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='detail',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='detail',
            name='size_body',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='detail',
            name='used',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
