# Generated by Django 4.2.8 on 2024-01-17 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_cart_avalable_remove_cart_buy_from_avalable_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
    ]
