# Generated by Django 4.2.8 on 2023-12-15 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_options_remove_user_date_joined_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='national_code',
            new_name='phone',
        ),
    ]
